/*
 * generated by Xtext 2.23.0
 */
package org.tvtower.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.autoedit.AbstractEditStrategyProvider;
import org.eclipse.xtext.ui.editor.hyperlinking.IHyperlinkHelper;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BmxUiModule extends AbstractBmxUiModule {

	public BmxUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public Class<? extends AbstractEditStrategyProvider> bindAbstractEditStrategyProvider() {
		return BmxEditStrategyProvider.class;
	}

	public Class<? extends IHyperlinkHelper> bindHyperlinkHelper() {
		return BmxHyperlinkHelper.class;
	}
}
