/*
 * generated by Xtext 2.23.0
 */
package org.tvtower;

import org.eclipse.xtext.linking.ILinkingDiagnosticMessageProvider;
import org.tvtower.validation.BmxLinkingErrorMessageProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BmxRuntimeModule extends AbstractBmxRuntimeModule {
	
	public Class<? extends ILinkingDiagnosticMessageProvider> bindLinkingErrorProvicer() {
		return BmxLinkingErrorMessageProvider.class;
	}
}
