/*
 * generated by Xtext 2.23.0
 */
package org.tvtower;

import org.eclipse.xtext.linking.ILinkingDiagnosticMessageProvider;
import org.eclipse.xtext.parser.antlr.Lexer;
import org.eclipse.xtext.parser.antlr.LexerBindings;
import org.eclipse.xtext.parser.antlr.LexerProvider;
import org.tvtower.parser.antlr.lexer.InternalBmxLexer;
import org.tvtower.validation.BmxLinkingErrorMessageProvider;

import com.google.inject.Binder;
import com.google.inject.Provider;
import com.google.inject.name.Names;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BmxRuntimeModule extends AbstractBmxRuntimeModule {

	@Override
	public Class<? extends Lexer> bindLexer() {
		return CustomBmxLexer.class;
	}

	@Override
	public Provider<? extends InternalBmxLexer> provideInternalBmxLexer() {
		return LexerProvider.create(CustomBmxLexer.class);
	}
	
	@Override
	public void configureRuntimeLexer(Binder binder) {
		binder.bind(Lexer.class)
			.annotatedWith(Names.named(LexerBindings.RUNTIME))
			.to(CustomBmxLexer.class);
	}

	public Class<? extends ILinkingDiagnosticMessageProvider> bindLinkingErrorProvicer() {
		return BmxLinkingErrorMessageProvider.class;
	}
}
