/*
 * generated by Xtext 2.23.0
 */
package org.tvtower;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BmxStandaloneSetup extends BmxStandaloneSetupGenerated {

	public static void doSetup() {
		new BmxStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
